package com.corocoro;

import java.util.HashMap;
import java.util.Map;

public class Consts {
    public static final Map<String, String> countryToCC = new HashMap<String, String>() {{
        put("east timor", "TP");
        put("mexico", "MX");
        put("french southern territories", "TF");
        put("tokelau", "TK");
        put("cayman islands", "KY");
        put("azerbaijan", "AZ");
        put("north korea", "KP");
        put("djibouti", "DJ");
        put("french guiana", "GF");
        put("asia", "UN142");
        put("guinea-bissau", "GW");
        put("japan", "JP");
        put("taiwan", "TW");
        put("cyprus", "CY");
        put("congo - brazzaville", "CG");
        put("barbados", "BB");
        put("peru", "PE");
        put("northern africa", "UN015");
        put("myanmar", "MM");
        put("bhutan", "BT");
        put("lithuania", "LT");
        put("congo - kinshasa", "CD");
        put("micronesia", "UN057");
        put("andorra", "AD");
        put("union of soviet socialist republics", "SU");
        put("burundi", "BI");
        put("rwanda", "RW");
        put("aruba", "AW");
        put("puerto rico", "PR");
        put("argentina", "AR");
        put("norway", "NO");
        put("sierra leone", "SL");
        put("ghana", "GH");
        put("falkland islands", "FK");
        put("belarus", "BY");
        put("saint helena", "SH");
        put("cuba", "CU");
        put("anguilla", "AI");
        put("middle africa", "UN017");
        put("french polynesia", "PF");
        put("southern europe", "UN039");
        put("guatemala", "GT");
        put("georgia", "GE");
        put("belgium", "BE");
        put("world", "UN001");
        put("haiti", "HT");
        put("southern asia", "UN034");
        put("kazakhstan", "KZ");
        put("burkina faso", "BF");
        put("liberia", "LR");
        put("kyrgyzstan", "KG");
        put("netherlands", "NL");
        put("kuwait", "KW");
        put("central america", "UN013");
        put("denmark", "DK");
        put("philippines", "PH");
        put("montserrat", "MS");
        put("senegal", "SN");
        put("moldova", "MD");
        put("latvia", "LV");
        put("croatia", "HR");
        put("bosnia and herzegovina", "BA");
        put("switzerland", "CH");
        put("western europe", "UN155");
        put("melanesia", "UN054");
        put("bulgaria", "BG");
        put("jamaica", "JM");
        put("albania", "AL");
        put("samoa", "WS");
        put("ivory coast", "CI");
        put("serbia and montenegro", "CS");
        put("northern america", "UN021");
        put("palestinian territory", "PS");
        put("lebanon", "LB");
        put("malaysia", "MY");
        put("australia", "AU");
        put("christmas island", "CX");
        put("yugoslavia", "YU");
        put("hungary", "HU");
        put("zaire", "ZR");
        put("greece", "GR");
        put("niger", "NE");
        put("canada", "CA");
        put("afghanistan", "AF");
        put("qatar", "QA");
        put("oceania", "UN009");
        put("palau", "PW");
        put("turkmenistan", "TM");
        put("equatorial guinea", "GQ");
        put("pitcairn", "PN");
        put("guinea", "GN");
        put("panama", "PA");
        put("nepal", "NP");
        put("central african republic", "CF");
        put("luxembourg", "LU");
        put("faroe islands", "FO");
        put("south america", "UN005");
        put("caribbean", "UN029");
        put("somalia", "SO");
        put("iceland", "IS");
        put("netherlands antilles", "AN");
        put("namibia", "NA");
        put("nauru", "NR");
        put("venezuela", "VE");
        put("australia and new zealand", "UN053");
        put("egypt", "EG");
        put("outlying oceania", "QO");
        put("europe", "UN150");
        put("brunei", "BN");
        put("iran", "IR");
        put("british indian ocean territory", "IO");
        put("united arab emirates", "AE");
        put("south georgia and the south sandwich islands", "GS");
        put("saint kitts and nevis", "KN");
        put("sri lanka", "LK");
        put("china", "CN");
        put("vietnam", "VN");
        put("armenia", "AM");
        put("grenada", "GD");
        put("western asia", "UN145");
        put("kiribati", "KI");
        put("belize", "BZ");
        put("bermuda", "BM");
        put("tunisia", "TN");
        put("bangladesh", "BD");
        put("ukraine", "UA");
        put("guadeloupe", "GP");
        put("northern mariana islands", "MP");
        put("libya", "LY");
        put("trinidad and tobago", "TT");
        put("mayotte", "YT");
        put("gambia", "GM");
        put("norfolk island", "NF");
        put("finland", "FI");
        put("macedonia", "MK");
        put("americas", "UN019");
        put("mauritius", "MU");
        put("antigua and barbuda", "AG");
        put("niue", "NU");
        put("estonia", "EE");
        put("syria", "SY");
        put("dominican republic", "DO");
        put("people's democratic republic of yemen", "YD");
        put("jersey", "JE");
        put("burma", "BU");
        put("pakistan", "PK");
        put("romania", "RO");
        put("seychelles", "SC");
        put("metropolitan france", "FX");
        put("czech republic", "CZ");
        put("eastern asia", "UN030");
        put("cook islands", "CK");
        put("neutral zone", "NT");
        put("guam", "GU");
        put("africa", "UN002");
        put("papua new guinea", "PG");
        put("united states", "US");
        put("austria", "AT");
        put("greenland", "GL");
        put("mongolia", "MN");
        put("colombia", "CO");
        put("thailand", "TH");
        put("angola", "AO");
        put("new zealand", "NZ");
        put("fiji", "FJ");
        put("comoros", "KM");
        put("turkey", "TR");
        put("united kingdom", "GB");
        put("madagascar", "MG");
        put("iraq", "IQ");
        put("chad", "TD");
        put("mauritania", "MR");
        put("eastern europe", "UN151");
        put("aland islands", "AX");
        put("france", "FR");
        put("bahamas", "BS");
        put("vatican", "VA");
        put("slovakia", "SK");
        put("gibraltar", "GI");
        put("swaziland", "SZ");
        put("laos", "LA");
        put("british virgin islands", "VG");
        put("south korea", "KR");
        put("bolivia", "BO");
        put("malawi", "MW");
        put("ecuador", "EC");
        put("israel", "IL");
        put("ireland", "IE");
        put("algeria", "DZ");
        put("serbia", "RS");
        put("poland", "PL");
        put("montenegro", "ME");
        put("tajikistan", "TJ");
        put("new caledonia", "NC");
        put("southern africa", "UN018");
        put("jordan", "JO");
        put("chile", "CL");
        put("martinique", "MQ");
        put("oman", "OM");
        put("turks and caicos islands", "TC");
        put("nigeria", "NG");
        put("spain", "ES");
        put("sao tome and principe", "ST");
        put("isle of man", "IM");
        put("eastern africa", "UN014");
        put("bouvet island", "BV");
        put("northern europe", "UN154");
        put("american samoa", "AS");
        put("polynesia", "UN061");
        put("morocco", "MA");
        put("sweden", "SE");
        put("cambodia", "KH");
        put("gabon", "GA");
        put("mali", "ML");
        put("mozambique", "MZ");
        put("yemen", "YE");
        put("hong kong", "HK");
        put("russia", "RU");
        put("u.s. virgin islands", "VI");
        put("cocos islands", "CC");
        put("bahrain", "BH");
        put("portugal", "PT");
        put("uruguay", "UY");
        put("central asia", "UN143");
        put("india", "IN");
        put("svalbard and jan mayen", "SJ");
        put("lesotho", "LS");
        put("western africa", "UN011");
        put("heard island and mcdonald islands", "HM");
        put("saint vincent and the grenadines", "VC");
        put("saint pierre and miquelon", "PM");
        put("uganda", "UG");
        put("paraguay", "PY");
        put("kenya", "KE");
        put("macao", "MO");
        put("botswana", "BW");
        put("italy", "IT");
        put("western sahara", "EH");
        put("south africa", "ZA");
        put("nicaragua", "NI");
        put("east germany", "DD");
        put("malta", "MT");
        put("ethiopia", "ET");
        put("guyana", "GY");
        put("vanuatu", "VU");
        put("marshall islands", "MH");
        put("cameroon", "CM");
        put("zambia", "ZM");
        put("antarctica", "AQ");
        put("benin", "BJ");
        put("brazil", "BR");
        put("singapore", "SG");
        put("solomon islands", "SB");
        put("tuvalu", "TV");
        put("saint lucia", "LC");
        put("saudi arabia", "SA");
        put("costa rica", "CR");
        put("united states minor outlying islands", "UM");
        put("slovenia", "SI");
        put("honduras", "HN");
        put("germany", "DE");
        put("wallis and futuna", "WF");
        put("san marino", "SM");
        put("dominica", "DM");
        put("suriname", "SR");
        put("eritrea", "ER");
        put("tonga", "TO");
        put("maldives", "MV");
        put("south-eastern asia", "UN035");
        put("uzbekistan", "UZ");
        put("togo", "TG");
        put("el salvador", "SV");
        put("tanzania", "TZ");
        put("indonesia", "ID");
        put("cape verde", "CV");
        put("sudan", "SD");
        put("liechtenstein", "LI");
        put("zimbabwe", "ZW");
        put("guernsey", "GG");
        put("monaco", "MC");
        put("reunion", "RE");
    }};

    private Consts() {
        throw new AssertionError();
    }
}
